name: jamesh
favicon: null
layout_spectrum: 0.12582619208842516
typography_spectrum: 0.3240631695371121
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.5398722500540316
  lightness: 0.5873912391252816
  saturation: 0.417102801380679
  rhythmicContrast: 0.1455541718751192
purpose: []
